title : Public Private Sector

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: public-private-sector
destination: public-private-sector

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://publicprivatesector.org

BASE_PATH : http://publicprivatesector.org

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
